import "../globals.css";
import Footer from "../components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-gray-100 text-gray-900 antialiased">
      <body className="min-h-screen flex flex-col">
        <main className="grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
